export type FieldGuideCategory = "science" | "history" | "stated goal" | "game abstraction";

export interface FieldGuideFact {
  id: string;
  title: string;
  body: string;
  category: FieldGuideCategory;
  sourceTitle: string;
  sourceUrl: string | null;
  verifiedDate: "2026-09-21";
}

const verifiedDate = "2026-09-21" as const;
const nasaMoon = "NASA Moon Facts";
const nasaMars = "NASA Mars Facts";
const moonUrl = "https://science.nasa.gov/moon/facts/";
const marsUrl = "https://science.nasa.gov/mars/facts/";

function fact(id: string, title: string, body: string, category: FieldGuideCategory, sourceTitle: string, sourceUrl: string | null): FieldGuideFact {
  return { id, title, body, category, sourceTitle, sourceUrl, verifiedDate };
}

export const FIELD_GUIDE: FieldGuideFact[] = [
  fact("moon-distance", "Average distance", "The Moon averages 238,855 miles (384,400 km) from Earth.", "science", nasaMoon, moonUrl),
  fact("moon-gravity", "Gravity", "Surface gravity is about one-sixth of Earth's.", "science", nasaMoon, moonUrl),
  fact("moon-air", "Air", "Its extremely thin exosphere cannot support human breathing.", "science", nasaMoon, moonUrl),
  fact("moon-far-side", "Far side", "The Moon rotates once per orbit, keeping roughly the same face toward Earth. The far side also receives sunlight.", "science", nasaMoon, moonUrl),
  fact("moon-water", "Water", "Permanently shadowed polar regions contain water ice.", "science", nasaMoon, moonUrl),
  fact("moon-surface", "Surface", "Lunar regolith consists of impact-broken rock and dust.", "science", nasaMoon, moonUrl),
  fact("moon-apollo", "Apollo samples", "Apollo crews returned about 842 pounds (382 kg) of lunar rock and soil.", "history", nasaMoon, moonUrl),
  fact("moon-first-landing", "First human landing", "Apollo 11 landed Neil Armstrong and Buzz Aldrin on the Moon on July 20, 1969. Michael Collins remained in lunar orbit.", "history", "NASA Apollo 11 Mission Overview", "https://www.nasa.gov/history/apollo-11-mission-overview/"),
  fact("moon-temperature", "Temperature", "Sunlit surface temperatures can reach about 260 F (127 C), while darkness can bring about -280 F (-173 C).", "science", nasaMoon, moonUrl),
  fact("mars-day", "A longer day", "A Martian sol lasts approximately 24.6 hours.", "science", nasaMars, marsUrl),
  fact("mars-year", "A longer year", "Mars takes about 687 Earth days to orbit the Sun.", "science", nasaMars, marsUrl),
  fact("mars-air", "Thin air", "Its thin atmosphere is mostly carbon dioxide, with nitrogen and argon.", "science", nasaMars, marsUrl),
  fact("mars-rust", "Rust-colored world", "Oxidized iron in surface rocks and dust gives Mars its reddish appearance.", "science", nasaMars, marsUrl),
  fact("mars-moons", "Two moons", "Phobos and Deimos are Mars's two small moons.", "science", nasaMars, marsUrl),
  fact("mars-water", "Ancient water", "River valleys, deltas, lakebeds, and minerals record a wetter past.", "science", nasaMars, marsUrl),
  fact("mars-dust", "Dust storms", "Storms can spread across much of the planet, and dust may take months to settle.", "science", nasaMars, marsUrl),
  fact("mars-namesake", "Namesake", "The Romans named Mars for their god of war.", "history", nasaMars, marsUrl),
  fact("spacex-2002", "2002", "SpaceX was founded in March 2002.", "history", "SpaceX CRS-4 press kit (2014)", "https://www.nasa.gov/wp-content/uploads/2018/07/spacex_nasa_crs-4_presskit.pdf"),
  fact("spacex-2008", "2008", "In September 2008, Falcon 1 became the first privately developed liquid-fueled rocket to reach Earth orbit.", "history", "SpaceX CRS-4 press kit (2014)", "https://www.nasa.gov/wp-content/uploads/2018/07/spacex_nasa_crs-4_presskit.pdf"),
  fact("spacex-2012", "2012", "Dragon completed a private-company supply mission to the International Space Station and returned to Earth in May 2012.", "history", "NASA Dragon mission (2012)", "https://www.nasa.gov/image-article/bolden-musk-dragon/"),
  fact("spacex-2020", "2020", "Demo-2 launched on May 30, 2020, carrying NASA astronauts Bob Behnken and Doug Hurley aboard Crew Dragon.", "history", "NASA Commercial Crew", "https://www.nasa.gov/commercial-crew-program-press-kit/"),
  fact("goal-settlement", "Self-sustaining settlement", "SpaceX has proposed a self-sustaining city on Mars as a long-term ambition, not an established settlement.", "stated goal", "SpaceX Making Life Multiplanetary (2016 proposal)", "https://www.spacex.com/media/making_life_multiplanetary_2016.pdf"),
  fact("goal-reuse", "Reuse at scale", "Its proposal identifies full vehicle reuse as essential to transporting people and cargo at the scale envisioned.", "stated goal", "SpaceX Making Life Multiplanetary (2016 proposal)", "https://www.spacex.com/media/making_life_multiplanetary_2016.pdf"),
  fact("game-abstraction", "Game design", "The game's transfer windows, travel durations, resource production, fusion power and helium-3 economy are compressed or speculative mechanics, not engineering forecasts. Art depicts imagined colonies, not existing infrastructure. Research unlocks are gameplay milestones, not evidence that a technology is deployed in real life.", "game abstraction", "Game design", null),

  // --- Ops depth folded from Grok 4.7 Field Notes ---
  fact("moon-shackleton-psrs", "Shackleton, PSRs, and LCROSS water", "Shackleton lies at the lunar south pole. Nearby permanently shadowed regions can preserve water ice in regolith. Orbital instruments reported south-polar ice signatures, and the 2009 LCROSS impact into Cabeus confirmed water in its ejecta. The charter's Shackleton Prospect is a fictional outpost placed on real geography, not a NASA facility or mission.", "science", "NASA LCROSS", "https://science.nasa.gov/mission/lcross/"),
  fact("moon-lunar-day-polar-light", "A lunar day is about 29.5 Earth days", "One lunar day, measured sunrise to sunrise, lasts about 29.5 Earth days. Polar terrain can offer unusual lighting conditions, while many sites face a long night. Power storage or another generation source is therefore a central planning concern. The charter compresses that environmental rhythm into its resource and power systems.", "science", nasaMoon, moonUrl),
  fact("moon-regolith-abrasive", "Regolith is feedstock and a hazard", "Lunar regolith is impact-broken rock and dust. Its sharp, abrasive particles can complicate equipment and suit operations, while the same bulk material may be useful for shielding, berms, or prepared surfaces. NASA studies lunar dust mitigation because it is an operational hazard. The charter treats regolith as both a resource and a maintenance problem.", "science", "NASA lunar dust mitigation", "https://www.nasa.gov/centers-and-facilities/kennedy/nasa-technology-helps-guard-against-lunar-dust/"),
  fact("moon-artemis-clps-hls", "Artemis, CLPS, and HLS are real programs", "NASA's Artemis campaign seeks crewed lunar exploration, including the south pole. Commercial Lunar Payload Services buys uncrewed cargo deliveries, while Human Landing System contracts cover crewed landers, including a Starship-derived design. They are separate programs with separate missions. Proxima Astra does not fly them; the charter places fictional operations beside, not inside, those real programs.", "history", "NASA Commercial Lunar Payload Services", "https://www.nasa.gov/commercial-lunar-payload-services/"),
  fact("moon-helium-3-ppb", "Helium-3 is parts per billion", "Solar wind implants helium-3 into lunar regolith at concentrations measured in parts per billion. Concentrations vary between samples and terrain. Recovering useful quantities would require processing substantial amounts of soil. NASA technical studies explore extraction concepts; those studies do not establish a commercially viable mining industry or a working helium-3 power economy.", "science", "NASA lunar helium-3 extraction study", "https://ntrs.nasa.gov/citations/20210022801"),
  fact("moon-cme-radiation-shelter", "Solar particle events need shelter", "The Moon lacks an atmosphere that would substantially reduce exposure to space radiation. Solar energetic particles and coronal mass ejections are related but distinct space-weather hazards. NASA studies shielding and sheltering for crews and equipment. In the charter, cover is a fictionalized operational trade; it is not a claim that arrays must always shut down during an event.", "science", "NASA solar wind", "https://science.nasa.gov/moon/solar-wind/"),
  fact("mars-optical-depth-opportunity", "Dust is an optical-depth problem", "Martian dust can reduce sunlight reaching a solar array. During the 2018 global storm, NASA's Opportunity rover lost power and contact after its solar arrays could not recharge it. That mission outcome does not establish that every storm has the same effect, and nuclear generation does not depend on sunlight. The charter simplifies this distinction for play.", "science", "NASA Opportunity end of mission", "https://www.nasa.gov/news-release/nasas-record-setting-opportunity-rover-mission-on-mars-comes-to-end/"),
  fact("mars-ice-latitude-phoenix", "Ice and landing-site selection", "Phoenix landed in Mars's northern plains in 2008 and exposed ice beneath the soil. That discovery does not mean every landing site has equally accessible water. Depth, distribution, and local conditions matter for future resource use. In the charter, placing a colony beside an ice tile simplifies the much harder task of surveying and selecting a real site.", "science", "NASA Phoenix Mars Lander", "https://www.nasa.gov/history/15-years-ago-phoenix-mars-lander-launches-to-the-red-planet/"),
  fact("mars-perchlorates", "Perchlorates in the soil", "Phoenix detected perchlorate salts in Martian soil in 2008. These salts matter because they affect how scientists interpret water chemistry and how future crews might handle local materials. Detection, characterization, and processing are engineering challenges; this note does not prescribe one cleanup method. The game does not simulate perchlorate chemistry or validate growing food in untreated Martian soil.", "science", "NASA Phoenix Mars Lander", "https://www.nasa.gov/history/15-years-ago-phoenix-mars-lander-launches-to-the-red-planet/"),
  fact("mars-rad-cruise-vs-surface", "Radiation varies by mission phase", "NASA's Mars-trip comparison describes roughly 180 days in transit each way and about 500 days on the surface as a representative mission pattern. Transit and surface exposure are different phases: the atmosphere and ground provide some shielding after landing, while duration, shielding, and solar conditions affect totals. A higher cruise dose rate is not an unconditional larger career dose.", "science", "NASA radiation exposure comparison", "https://science.nasa.gov/resource/radiation-exposure-comparisons-with-mars-trip-calculation/"),
  fact("mars-sabatier-moxie", "Sabatier methane and MOXIE oxygen", "The Sabatier reaction and MOXIE are separate technologies. Sabatier chemistry can combine carbon dioxide and hydrogen to make methane and water. MOXIE demonstrated solid-oxide electrolysis of Martian carbon dioxide to produce oxygen, reaching about 126 grams over its mission. That was a technology demonstration, not a propellant depot or a complete local-fuel system.", "science", "NASA MOXIE on Perseverance", "https://www.nasa.gov/missions/mars-2020-perseverance/perseverance-rover/nasas-oxygen-generating-experiment-moxie-completes-mars-mission/"),
  fact("mars-synodic-window-26mo", "The real Earth-Mars window is about 26 months", "Earth and Mars reach favorable launch geometry about every 26 months. A real transfer takes several months, with duration depending on trajectory and mission design. The Moon is much closer by conventional transfer. Proxima compresses both the calendar and travel legs so a campaign fits a session; its short cycles are game timing, not a Hohmann forecast.", "science", "NASA Mars mission timeline", "https://science.nasa.gov/planetary-science/programs/mars-exploration/mission-timeline/"),
  fact("mars-eclss-still-resupply", "Closed-loop ECLSS still needs resupply", "NASA's ECLSS work recycles water and regenerates oxygen, but a spacecraft life-support system is not a perfectly closed ecology. Hardware needs maintenance, replacement parts, and consumables or resupply planning. The charter abstracts recovery into a technology effect; it does not claim a precise recovery percentage or imply that a base becomes permanently self-sufficient.", "science", "NASA ECLSS reference", "https://www.nasa.gov/reference/environmental-control-and-life-support-systems-eclss/"),
  fact("spacex-starship-super-heavy", "Starship and Super Heavy", "SpaceX describes Starship as a spacecraft and Super Heavy as its booster, using methane and liquid oxygen in Raptor engines. Reuse and refueling are stated design goals. This note describes the company's published architecture, not an operationally proven Moon or Mars transport service. Proxima's Starship-like hulls are fictional game vehicles and are not SpaceX missions.", "history", "SpaceX Starship", "https://www.spacex.com/vehicles/starship/"),
  fact("spacex-why-methane", "Why the propellant is methane", "Methane and oxygen can, in principle, be made from carbon dioxide and water, which makes methane attractive in destination-resource studies. SpaceX's Starship materials identify methalox as the vehicle propellant and describe Mars production as an ambition. That is a design rationale, not proof that Mars fuel production or routine refueling is operational.", "science", "SpaceX Starship", "https://www.spacex.com/vehicles/starship/"),
  fact("spacex-aldrin-cycler", "An Aldrin cycler is a repeating trajectory", "A Mars cycler is a proposed trajectory that repeatedly passes Earth and Mars. A habitat could remain on the repeating path while smaller vehicles rendezvous with it, reducing the need to launch the habitat each window. NASA technical literature records cycler studies as concepts and analyses. No claim is made here that SpaceX operates a cycler today.", "history", "NASA Mars cycler study", "https://ntrs.nasa.gov/citations/19930054986"),
  fact("spacex-nerva-ntr", "Nuclear thermal is a different architecture", "A nuclear-thermal rocket heats propellant in a reactor, usually hydrogen, to achieve higher exhaust speed than a chemical engine. NERVA-era systems were ground-tested but did not fly. NASA technical history documents that program, while SpaceX's published Starship architecture is chemical methalox. NTR is therefore a separate propulsion branch, not a description of this vehicle.", "history", "NASA NERVA history", "https://ntrs.nasa.gov/citations/20140008771"),
  fact("moon-sintered-pads-plume", "Landing plumes disturb regolith", "Rocket plumes can erode and eject loose lunar soil during landing. NASA is testing plume-surface interactions and studying mitigation approaches such as prepared pads and protective layouts. These are investigated techniques, not a categorical claim that every landing creates the same crater or that a particular remedy is deployed. The charter turns that research problem into a construction choice.", "science", "NASA plume-surface interaction tests", "https://www.nasa.gov/missions/artemis/nasa-begins-moon-mission-plume-surface-interaction-tests/"),
  fact("game-compressed-windows", "The charter compresses windows and travel", "In the game, Luna trips, Mars windows, and cruise times are shortened so a campaign fits a session. Flying off-window may still work but costs time and risk. Treat the board calendar as a compression of the real ~26-month Earth-Mars rhythm, not as astronomy.", "game abstraction", "Game design", null),
  fact("game-he3-export-abstraction", "He-3 export is compressed for the campaign", "The charter's helium-3 extractor is an abstraction of an industrial problem scaled so a campaign can feel the export, not a claim that lunar grades are rich or that fusion power is online. Real He-3 concentrations stay in the parts-per-billion range.", "game abstraction", "Game design", null),
  fact("game-processor-not-terraform", "A processor is not a terraformed planet", "Giving a habitat a local oxygen loop, or staining a greenhouse with algae, changes a base. Changing Mars into a shirt-sleeve planet would mean moving or making an atmosphere's worth of gas and holding it against loss for centuries. No module does that. An atmosphere processor in the charter is life support with a view — do not let the word terraforming outrun the physics.", "game abstraction", "Game design", null),
];

export const FIELD_GUIDE_CATEGORIES = ["Moon", "Mars", "SpaceX", "Game vs reality"] as const;

export function guideCategory(factItem: FieldGuideFact): (typeof FIELD_GUIDE_CATEGORIES)[number] {
  if (factItem.id.startsWith("moon-")) return "Moon";
  if (factItem.id.startsWith("mars-")) return "Mars";
  if (factItem.id.startsWith("spacex-") || factItem.id.startsWith("goal-")) return "SpaceX";
  return "Game vs reality";
}
