import { assert } from "./testAssert";
import { foundColony, landingAdvice, placeBuilding, placementError } from "./actions";
import { buildingImpact, constructionGuidance } from "./guidance";
import { applyTurn, forecast, suggestions } from "./sim";
import { createGame, emptyCargo } from "./state";

// Synthetic founding-kit fixture tests the budget trap from the browser audit.
const game = createGame("charter", 682984644);
const ship = game.ships[0]!;
ship.loc = "mars";
ship.crew = 11;
ship.cargo = { ...emptyCargo(), metals: 44, water: 28, food: 24, oxygen: 40 };
game.founding = { shipId: ship.id, world: "mars" };
const site = game.worlds.mars.tiles.find(t => landingAdvice(game, "mars", t.q, t.r) === "good")!;
assert.equal(foundColony(game, site.q, site.r).ok, true);
const first = constructionGuidance(game, "mars");
assert.equal(first.building, "ice");
assert.ok(first.site);
assert.equal(placeBuilding(game, "mars", first.site.q, first.site.r, first.building!).ok, true);
const second = constructionGuidance(game, "mars");
assert.equal(second.building, "regolith", "fund the producer before the greenhouse/ISRU consume the reserve");
assert.ok(second.site);
const before = JSON.stringify(game);
const impact = buildingImpact(game, "mars", second.site.q, second.site.r, second.building!);
assert.equal(JSON.stringify(game), before, "previews never mutate the campaign");
assert.ok(impact && impact.after.produced.metals > impact.before.produced.metals);
assert.equal(placeBuilding(game, "mars", second.site.q, second.site.r, second.building!).ok, true);
const third = constructionGuidance(game, "mars");
assert.equal(third.building, "greenhouse");
assert.ok(third.site);
assert.equal(placeBuilding(game, "mars", third.site.q, third.site.r, third.building!).ok, true);
assert.equal(game.worlds.mars.stock.metals, 8);
const waiting = constructionGuidance(game, "mars");
assert.equal(waiting.building, "isru");
assert.equal(waiting.site, null);
assert.match(waiting.blocker!, /more tonnes of metals/);
assert.equal(waiting.building === first.building, false, "pending mines do not duplicate");
applyTurn(game);
game.events = [];
const funded = constructionGuidance(game, "mars");
assert.equal(funded.building, "isru");
assert.ok(funded.site, "completed works fund oxygen production after one sol");
assert.equal(placementError(game, "mars", funded.site.q, funded.site.r, funded.building!), null);

// Feedstock-limited ISRU must not be 'fixed' by adding another consumer.
const limited = createGame("charter", 42);
const world = limited.worlds.luna;
world.stock.regolith = 0;
world.stock.water = 130;
const legal = world.tiles.find(t => placementError(limited, "luna", t.q, t.r, "isru") === null)!;
assert.equal(placeBuilding(limited, "luna", legal.q, legal.r, "isru").ok, true);
legal.building!.progress = 0;
assert.equal(forecast(limited, "luna").produced.oxygen, 0);
assert.equal(suggestions(limited, "luna").includes("isru"), false);
const feedstockAdvice = constructionGuidance(limited, "luna");
assert.equal(feedstockAdvice.building, "ice", "establish the missing water producer first");
assert.ok(feedstockAdvice.site);
assert.equal(placeBuilding(limited, "luna", feedstockAdvice.site.q, feedstockAdvice.site.r, feedstockAdvice.building!).ok, true);
assert.equal(constructionGuidance(limited, "luna").building, "regolith", "then add soil feedstock instead of another ISRU");
console.log("guidance: producer budget, pending dependencies, blocked advice, feedstock and read-only previews pass");
