import { assert } from "./testAssert";
import { launchShip, previewLaunch, sellCargo } from "./actions";
import { operationsBrief, exportPlan } from "./operations";
import { createGame } from "./state";
import { DIFF, SHIPS } from "./data";
import { forecast } from "./sim";
import type { BuildingId } from "./types";

for (const difficulty of ["survey", "charter", "hardship"] as const) {
  const game = createGame(difficulty, 42);
  const before = JSON.stringify(game);
  const brief = operationsBrief(game);
  assert.equal(JSON.stringify(game), before, "Advice must not alter saves, stock, ships or RNG");
  assert.equal(brief.population[0].target, DIFF[difficulty].lunaPop);
  assert.equal(brief.population[1].target, DIFF[difficulty].marsPop);
  assert.equal(brief.exports[0].ready, false, "No speculative future He3 counted");
  assert.equal(brief.exports[0].sale, 0);
  assert.match(brief.exportNext, /Regolith Sintering/);
  assert.equal(brief.cash.debtFee, 0);
  assert.equal(brief.fleet.target, DIFF[difficulty].ships);
}

// Synthetic stock fixtures test the manifest contract, not campaign balance.
const game = createGame("charter", 42);
const ship = game.ships[0];
game.worlds.luna.stock.he3 = 41.5;
let plan = exportPlan(game, ship.id)!;
assert.ok(plan.ready);
assert.equal(plan.kilograms, SHIPS.courier.cargo);
assert.equal(plan.sale, plan.kilograms * 42);
assert.ok(previewLaunch(game, ship.id, plan.draft).ok);
assert.equal(plan.cashOutlay, 0);
const credits = game.credits;
assert.ok(launchShip(game, ship.id, plan.draft).ok);
assert.equal(game.credits, credits, "An export does not pay until sold at Earth");
assert.equal(exportPlan(game, ship.id), null, "No preparations for in-flight ships");
ship.loc = "earth";
ship.mission = null;
assert.ok(sellCargo(game, ship.id).ok);
assert.equal(game.credits - credits, plan.sale);
game.worlds.luna.stock.he3 = 12;
ship.fuel = 0;
plan = exportPlan(game, ship.id)!;
assert.ok(plan.ready);
assert.equal(plan.draft.fuel, plan.fuelBurn, "Earth preparation covers both legs, not only outbound");
assert.equal(plan.saleSol, game.turn + 2);
assert.equal(plan.cashOutlay, previewLaunch(game, ship.id, plan.draft).cost);
assert.ok(plan.cashOutlay > 0);
assert.equal(plan.legRisks.length, 2);
const founder = { ...ship, id: "founder", cls: "colony" as const, hull: SHIPS.colony.hull };
game.ships.push(founder);
assert.match(exportPlan(game, founder.id)!.blocker!, /Reserve the colony ship/);
game.worlds.mars.founded = true;
assert.ok(exportPlan(game, founder.id)!.ready, "A founded Mars releases the colony hull for discretionary pickup runs");
game.worlds.mars.founded = false;
game.ships.pop();
const pad = game.worlds.luna.tiles.find(t => t.building?.type === "pad")!.building!;
pad.progress = 1;
assert.match(exportPlan(game, ship.id)!.blocker!, /finished launch pad/);
pad.progress = 0;
game.credits = DIFF.charter.overdraft;
assert.equal(exportPlan(game, ship.id)!.ready, false, "New fuel still needs available credit");
game.credits = -400;
assert.equal(operationsBrief(game).cash.debtFee, 16);
game.credits = -10;
assert.equal(operationsBrief(game).cash.debtFee, 12);
game.credits = -2000;
assert.equal(operationsBrief(game).cash.debtFee, 60);
game.credits = 1000;
game.earthLaunches = 2;
assert.match(exportPlan(game, ship.id)!.blocker!, /two hulls/);
game.earthLaunches = 0;
game.founding = { shipId: ship.id, world: "luna" };
assert.equal(exportPlan(game, ship.id), null);
game.founding = null;
ship.cargo.food = 2;
assert.equal(exportPlan(game, ship.id), null, "Do not replace a loaded Earth manifest with a trade run");
ship.cargo.food = 0;
ship.loc = "luna";
game.worlds.luna.launches = 1;
assert.match(exportPlan(game, ship.id)!.blocker!, /already fired/);
game.outcome = { kind: "victory" };
assert.equal(exportPlan(game, ship.id), null);
const housingGame = createGame("charter", 7);
const housingTile = housingGame.worlds.luna.tiles.find(t => !t.building)!;
housingTile.building = { type: "habitat", hp: 100, progress: 1, total: 2 };
const housingBefore = JSON.stringify(housingGame);
const housingAdvice = operationsBrief(housingGame).population[0];
assert.equal(housingAdvice.housing, 18, "Final-sol construction is not counted as completed housing");
assert.equal(housingAdvice.pendingHousing, 14);
assert.equal(JSON.stringify(housingGame), housingBefore);

// A full battery can power a sol without making generation sustainable.
const powerGame = createGame("charter", 42);
const world = powerGame.worlds.luna;
for (const tile of world.tiles) tile.building = null;
const modules: BuildingId[] = ["command", "habitat", "habitat", "greenhouse", "greenhouse", ...Array<BuildingId>(6).fill("ice"), ...Array<BuildingId>(4).fill("isru"), ...Array<BuildingId>(4).fill("solar")];
modules.forEach((type, i) => {
  const tile = world.tiles[i];
  tile.terrain = "mare";
  tile.ice = 100;
  tile.building = { type, hp: 100, progress: 0, total: 0 };
});
powerGame.tech.unlocked = ["hydro"];
world.dust = world.radiation = world.shelter = world.quarantine = 0;
world.stock.energy = 100;
world.stock.water = world.stock.regolith = 100;
const targetGame = structuredClone(powerGame);
targetGame.worlds.luna.pop = DIFF.charter.lunaPop;
const currentDraw = forecast(powerGame, "luna").energyDraw;
const targetDraw = forecast(targetGame, "luna").energyDraw;
const solarTiles = world.tiles.filter(t => t.building?.type === "solar");
const generationBetween = (currentDraw + targetDraw) / 2;
for (const tile of solarTiles) tile.building!.hp = (generationBetween - 12) / (11 * solarTiles.length) * 100;
const targetPowerAdvice = operationsBrief(powerGame).population[0];
assert.ok(Object.values(targetPowerAdvice.targetNet).every(n => n >= 0), "Fixture isolates power from consumable deficits");
assert.equal(forecast(powerGame, "luna").brownout, false);
assert.ok(forecast(powerGame, "luna").energyGen > currentDraw);
assert.ok(targetPowerAdvice.targetPower.generation < targetPowerAdvice.targetPower.demand);
assert.match(targetPowerAdvice.next, /before hiring crew/);
for (const tile of solarTiles) tile.building!.hp = (currentDraw - 1 - 12) / (11 * solarTiles.length) * 100;
assert.equal(forecast(powerGame, "luna").brownout, false, "Stored energy masks today's generation deficit");
assert.match(operationsBrief(powerGame).population[0].next, /sustained power.*before expanding/);
console.log("operations: nonmutating goal advice, exact export manifests, deferred sale, return fuel, debt and launch blockers pass");
